name: CI
on:
  pull_request:
    brances:
      - release
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: npx deno test
        